---
# tasks file for swapfile-ansible-role

- name: Configure vm.swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swapfile_swappiness | default(omit) }}"
    state: "{% if swapfile_swappiness is defined and swapfile_swappiness %}present{% else %}absent{% endif %}"

- name: Configure vm.vfs_cache_pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ swapfile_vfs_cache_pressure | default(omit) }}"
    state: "{% if swapfile_vfs_cache_pressure is defined and swapfile_vfs_cache_pressure %}present{% else %}absent{% endif %}"
